apiVersion: v1
kind: Service
metadata:
  name: productinfo-api
  namespace: productinfo
spec:
  type: ClusterIP
  selector:
    app: productinfo-api
  ports:
    - name: http
      port: 5000
      targetPort: 5000
