apiVersion: v1
kind: Service
metadata:
  name: productinfo-api-nodeport
  namespace: productinfo
spec:
  type: NodePort
  selector:
    app: productinfo-api
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30500
