apiVersion: v1
kind: Secret
metadata:
  name: sqlserver-secret
  namespace: productinfo
type: Opaque
stringData:
  SA_PASSWORD: "Your_strong_password123"
  ConnectionStrings__ProductDb: "Server=sqlserver,1433;Database=ProductInfoDb;User Id=sa;Password=Your_strong_password123;TrustServerCertificate=True;MultipleActiveResultSets=True"
